name: macOS Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-macOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Build library
        run: |
          cmake -B build -D CMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug
          rm -rf build
          cmake -B build -D CMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
