name: Linux Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
env:
  platform: Linux
  Qt_patch_version: 5.15.16
  
jobs:
  Build-Linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get -y install libgl1-mesa-dev freeglut3-dev libwayland-dev libxkbcommon-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
          git clone https://github.com/glfw/glfw.git
          
      - name: Build library
        run: |
          git clone https://github.com/faojdoai324234s/Qt-${{ env.platform }}.git
          cmake -B build -D Qt5_DIR="Qt-${{ env.platform }}/Qt-${{ env.Qt_patch_version }}/lib/cmake/Qt5" -D CMAKE_BUILD_TYPE=Debug
          cmake --build build --config Debug
          rm -rf build
          cmake -B build -D Qt5_DIR="Qt-${{ env.platform }}/Qt-${{ env.Qt_patch_version }}/lib/cmake/Qt5" -D CMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
