name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-Win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Build library
        shell: cmd
        run: |
          git clone https://github.com/faojdoai324234s/Qt-Win.git
          cmake -B build -D Qt5_DIR="Qt-Win/Qt-5.15.16/lib/cmake/Qt5"
          cmake --build build --config Debug
          rmdir /s /q build
          cmake -B build -D Qt5_DIR="Qt-Win/Qt-5.15.16/lib/cmake/Qt5"
          cmake --build build --config Release
